openapi: 3.0.0
info:
  title: Phone Inventory Service API
  version: 1.0.0

servers:
  - url: http://localhost:8082/phone-store

tags:
  - name: Phone-Store
    externalDocs:
      description: Find out more
      url: https://swagger.io

paths:
  /store/createStore:
    post:
      summary: Create one or more new stores
      operationId: addItems
      tags:
        - Phone-Store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PhoneStoreItem'
      responses:
        '201':
          description: Items added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Items added successfully
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /store/{id}:
    get:
      summary: Get store details
      operationId: getItemById
      tags:
        - Phone-Store
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhoneStoreItem'
        '400':
          description: Invalid ObjectId format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Store not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete store from DB
      operationId: deleteItemById
      tags:
        - Phone-Store
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Store deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Store deleted successfully
        '404':
          description: Store not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /store/updateStore:
    put:
      summary: Update store details
      operationId: updateStoreDetails
      tags:
        - Phone-Store
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhoneStoreItem'
      responses:
        '200':
          description: Store updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Store updated successfully
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Store not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    PhoneStoreItem:
      type: object
      properties:
        storeName:
          type: string
          minLength: 10
          maxLength: 50
          example: Store-A
        address:
          type: string
          minLength: 10
          maxLength: 50
          example: ABC-Block D Street
        managerName:
          type: string
          minLength: 5
          maxLength: 15
          example: Mark
      required:
        - storeName
        - address
        - managerName

    Error:
      type: object
      properties:
        code:
          type: string
          example: "400"
        message:
          type: string
          example: Validation failed for fields...
      required:
        - code
        - message
